"""add Department

Revision ID: 033e5deb3454
Revises: 8bf9cbc3727f
Create Date: 2024-04-02 22:37:27.895732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033e5deb3454'
down_revision = '8bf9cbc3727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
